coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        base: auto
        branches:
          - main
        flags:
          - react-rtc
        paths:
          - packages/react-rtc
    patch: off

comment: false
