coverage:
  status:
    project:
      react-rtc:
        target: auto
        threshold: 10%
        base: auto
        flags:
          - react-rtc
        paths:
          - packages/react-rtc
      signaling-server:
        target: auto
        threshold: 10%
        base: auto
        flags:
          - signaling-server
        paths:
          - packages/signaling-server

comment: false
