coverage:
  status:
    project:
      default: false
      react-rtc:
        target: auto
        flags:
          - react-rtc
        paths:
          - packages/react-rtc
      signaling-server:
        target: auto
        flags:
          - signaling-server
        paths:
          - packages/signaling-server
    patch: off

comment: false
