coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
        base: auto
        branches:
          - main
        flags:
          - react-rtc
          - signaling-server
        paths:
          - packages/react-rtc
          - packages/signaling-server

comment: false
