on:
  push:
    branches: ['**']
    tags:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup.yml
      - name: Run type check
        run: yarn tsc:check
      - name: Run eslint
        run: yarn lint
      - name: Run tests
        run: yarn test

  deploy_preview:
        runs-on: ubuntu-latest
        needs: test
        if: startsWith(github.ref, 'refs/tags/') == false
        environment:
            name: Preview
            url: ${{ steps.deploy.outputs.preview-url }}
        steps:
            - uses: actions/checkout@v3
            - id: deploy
              uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}

  deploy_production:
        runs-on: ubuntu-latest
        needs: test
        if: startsWith(github.ref, 'refs/tags/')
        environment:
            name: Production
            url: https://react-rtc.vercel.app/
        steps:
            - uses: actions/checkout@v3
            - id: deploy
              uses: amondnet/vercel-action@v20
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
                  vercel-args: '--prod'
